services:
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    environment:
      MYSQL_DATABASE: web_doc_truyen
      MYSQL_USER: vinh
      MYSQL_PASSWORD: vinh123
      MYSQL_ROOT_PASSWORD: vinh123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      - spring-web_truyen

  web_truyen:
    container_name: web_truyen
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - spring-web_truyen
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/web_doc_truyen?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC
      SPRING_DATASOURCE_USERNAME: vinh
      SPRING_DATASOURCE_PASSWORD: vinh123
      SPRING_APPLICATION_NAME: web_truyen

networks:
  spring-web_truyen:
    driver: bridge
